# Generated by Django 5.1.6 on 2025-04-16 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_section', models.CharField(choices=[('ADMIN', 'Admin'), ('TECHNICAL', 'Technical'), ('PHYSICAL', 'Physical'), ('ATOMIC', 'Atomic Absorption'), ('STANDARD', 'Standard Lab'), ('MICROBIOLOGY', 'Microbiology Lab'), ('CHEMICAL', 'Chemical Lab'), ('GA', 'Government Analyst'), ('HPLC', 'HPLC Lab'), ('QMS', 'QMS Section'), ('STORES', 'Stores'), ('PROCUREMENT', 'Procurement'), ('DIRECTOR', 'Director')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('unique_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('ADMIN', 'Admin'), ('TECHNICAL', 'Technical'), ('PHYSICAL', 'Physical'), ('ATOMIC', 'Atomic Absorption'), ('STANDARD', 'Standard Lab'), ('MICROBIOLOGY', 'Microbiology Lab'), ('CHEMICAL', 'Chemical Lab'), ('GA', 'Government Analyst'), ('HPLC', 'HPLC Lab'), ('QMS', 'QMS Section'), ('STORES', 'Stores'), ('PROCUREMENT', 'Procurement'), ('DIRECTOR', 'Director')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
