# Generated by Django 5.1.6 on 2025-04-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='to_section',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TECHNICAL', 'Technical'), ('PHYSICAL', 'Physical'), ('ATOMIC', 'Atomic Absorption'), ('STANDARD', 'Standard Lab'), ('MICROBIOLOGY', 'Microbiology Lab'), ('CHEMICAL', 'Chemical Lab'), ('GA', 'Government Analyst'), ('HPLC', 'HPLC Lab'), ('QMS', 'QMS Section'), ('STORES', 'Stores'), ('PROCUREMENT', 'Procurement'), ('DIRECTOR', 'Director'), ('SRO', 'Sample Receiving Officer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='section',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TECHNICAL', 'Technical'), ('PHYSICAL', 'Physical'), ('ATOMIC', 'Atomic Absorption'), ('STANDARD', 'Standard Lab'), ('MICROBIOLOGY', 'Microbiology Lab'), ('CHEMICAL', 'Chemical Lab'), ('GA', 'Government Analyst'), ('HPLC', 'HPLC Lab'), ('QMS', 'QMS Section'), ('STORES', 'Stores'), ('PROCUREMENT', 'Procurement'), ('DIRECTOR', 'Director'), ('SRO', 'Sample Receiving Officer')], max_length=20),
        ),
    ]
