# Generated by Django 5.1.6 on 2025-04-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_note_status_alter_note_to_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_section_incharge',
            field=models.BooleanField(default=False),
        ),
    ]
