# Generated by Django 5.1.6 on 2025-04-16 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_userprofile_is_section_incharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_section_incharge',
        ),
        migrations.AddField(
            model_name='note',
            name='receiver_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='to_section',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TECHNICAL', 'Technical'), ('PHYSICAL', 'Physical'), ('ATOMIC', 'Atomic Absorption'), ('STANDARD', 'Standard Lab'), ('MICROBIOLOGY', 'Microbiology Lab'), ('HPLC', 'HPLC Lab'), ('QMS', 'QMS Section'), ('STORES', 'Stores'), ('PROCUREMENT', 'Procurement'), ('DIRECTOR', 'Director')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='section',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TECHNICAL', 'Technical'), ('PHYSICAL', 'Physical'), ('ATOMIC', 'Atomic Absorption'), ('STANDARD', 'Standard Lab'), ('MICROBIOLOGY', 'Microbiology Lab'), ('HPLC', 'HPLC Lab'), ('QMS', 'QMS Section'), ('STORES', 'Stores'), ('PROCUREMENT', 'Procurement'), ('DIRECTOR', 'Director')], max_length=20),
        ),
        migrations.CreateModel(
            name='NoteForwardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_section', models.CharField(choices=[('ADMIN', 'Admin'), ('TECHNICAL', 'Technical'), ('PHYSICAL', 'Physical'), ('ATOMIC', 'Atomic Absorption'), ('STANDARD', 'Standard Lab'), ('MICROBIOLOGY', 'Microbiology Lab'), ('HPLC', 'HPLC Lab'), ('QMS', 'QMS Section'), ('STORES', 'Stores'), ('PROCUREMENT', 'Procurement'), ('DIRECTOR', 'Director')], max_length=20)),
                ('to_section', models.CharField(choices=[('ADMIN', 'Admin'), ('TECHNICAL', 'Technical'), ('PHYSICAL', 'Physical'), ('ATOMIC', 'Atomic Absorption'), ('STANDARD', 'Standard Lab'), ('MICROBIOLOGY', 'Microbiology Lab'), ('HPLC', 'HPLC Lab'), ('QMS', 'QMS Section'), ('STORES', 'Stores'), ('PROCUREMENT', 'Procurement'), ('DIRECTOR', 'Director')], max_length=20)),
                ('forwarded_at', models.DateTimeField(auto_now_add=True)),
                ('forwarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_history', to='communication.note')),
            ],
        ),
    ]
