# Generated by Django 5.1.6 on 2025-04-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_remove_userprofile_is_section_incharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='unique_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
