# Generated by Django 5.1.6 on 2025-04-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_alter_note_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='to_section',
            field=models.CharField(choices=[('BME', 'Biomedical Engineering'), ('ZAD', 'Zain ul Abadin'), ('FAH', 'Faizan Hairder'), ('KHI', 'Khansa Ibrahim'), ('STANDARD', 'Standard Lab'), ('MICROBIOLOGY', 'Microbiology Lab'), ('HPLC', 'HPLC Lab'), ('QMS', 'QMS Section'), ('STORES', 'Stores'), ('PROCUREMENT', 'Procurement'), ('DIRECTOR', 'Director')], max_length=20),
        ),
        migrations.AlterField(
            model_name='noteforwardhistory',
            name='from_section',
            field=models.CharField(choices=[('BME', 'Biomedical Engineering'), ('ZAD', 'Zain ul Abadin'), ('FAH', 'Faizan Hairder'), ('KHI', 'Khansa Ibrahim'), ('STANDARD', 'Standard Lab'), ('MICROBIOLOGY', 'Microbiology Lab'), ('HPLC', 'HPLC Lab'), ('QMS', 'QMS Section'), ('STORES', 'Stores'), ('PROCUREMENT', 'Procurement'), ('DIRECTOR', 'Director')], max_length=20),
        ),
        migrations.AlterField(
            model_name='noteforwardhistory',
            name='to_section',
            field=models.CharField(choices=[('BME', 'Biomedical Engineering'), ('ZAD', 'Zain ul Abadin'), ('FAH', 'Faizan Hairder'), ('KHI', 'Khansa Ibrahim'), ('STANDARD', 'Standard Lab'), ('MICROBIOLOGY', 'Microbiology Lab'), ('HPLC', 'HPLC Lab'), ('QMS', 'QMS Section'), ('STORES', 'Stores'), ('PROCUREMENT', 'Procurement'), ('DIRECTOR', 'Director')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='section',
            field=models.CharField(choices=[('BME', 'Biomedical Engineering'), ('ZAD', 'Zain ul Abadin'), ('FAH', 'Faizan Hairder'), ('KHI', 'Khansa Ibrahim'), ('STANDARD', 'Standard Lab'), ('MICROBIOLOGY', 'Microbiology Lab'), ('HPLC', 'HPLC Lab'), ('QMS', 'QMS Section'), ('STORES', 'Stores'), ('PROCUREMENT', 'Procurement'), ('DIRECTOR', 'Director')], max_length=20),
        ),
    ]
