# Generated by Django 5.1.6 on 2025-04-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0009_itemrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='ID',
            field=models.CharField(default='untitled', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
