# Generated by Django 5.1.6 on 2025-04-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_inventoryitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='ID',
            field=models.CharField(max_length=100),
        ),
    ]
