# Generated by Django 5.1.6 on 2025-04-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0011_alter_inventoryitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='ID',
        ),
    ]
